version: '3.7'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker 
    ports:
      - "80:80"     # The HTTP port
      - "8888:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  
  app:
    build:
      context: ./demo
    volumes:
      - ./demo:/usr/share/nginx/html
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:demo.haxcms.localhost"
      - "traefik.port=80"
    environment:
      - HAXCMS_ON_DEMAND_FQDN=http://hod.2019.hax.camp
      - HAXCMS_AUTH_FQDN=http://auth.2019.hax.camp

  server:
    build: .
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock # connect docker to the host machine docker thread
      - /usr/local/bin/docker:/usr/bin/docker # give the container access to docker
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:hod.haxcms.localhost"
      - "traefik.port=4000"
      - "traefik.frontend.passHostHeader=true"
    environment:
      - PRISMA_DB_PROVIDER=postgresql
      - PRISMA_DB_URL=postgresql://prisma:prisma@postgres/
      - HAXCMS_OAUTH_JWT_SECRET=1598559ab3894f59bde1f42638c4cf9e
      - FQDN=http://hod.haxcms.localhost
      - NETWORK=haxcms-on-demand_default
      - ADMINS=heyMP,btopro
    depends_on:
      - postgres

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /var/lib/postgresql/data
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.port=5432"